// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    EditarProyectos: typeof import('C:/SANTIAGO/Proyectos/tests/sgarcia-tech/client/src/components/EditarProyectos.vue')['default']
    Proyectos: typeof import('C:/SANTIAGO/Proyectos/tests/sgarcia-tech/client/src/components/Proyectos.vue')['default']
    Top: typeof import('C:/SANTIAGO/Proyectos/tests/template-vue-vite-node/client/src/components/Top.vue')['default']
  }
}

export { }
