// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Counter: typeof import('C:/SANTIAGO/Proyectos/template-vue-vite-node/client/src/components/Counter.vue')['default']
    GetUser: typeof import('C:/SANTIAGO/Proyectos/template-vue-vite-node/client/src/components/GetUser.vue')['default']
    Top: typeof import('C:/SANTIAGO/Proyectos/template-vue-vite-node/client/src/components/Top.vue')['default']
  }
}

export { }
